In [1]:
import pandas as pd

In [2]:
flights_MIA_201807 = pd.read_csv('Miami_201807.csv')
flights_MIA_201807.shape
flights_MIA_201807.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,...,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 50
0,2018,3,7,1,7,2018-07-01,9E,20363,9E,N295PQ,...,39.0,1.0,223.0,1,NaN,NaN,NaN,NaN,NaN,NaN
1,2018,3,7,8,7,2018-07-08,9E,20363,9E,N337PQ,...,142.0,1.0,1028.0,5,NaN,NaN,NaN,NaN,NaN,NaN
2,2018,3,7,14,6,2018-07-14,9E,20363,9E,N296PQ,...,136.0,1.0,1028.0,5,NaN,NaN,NaN,NaN,NaN,NaN
3,2018,3,7,15,7,2018-07-15,9E,20363,9E,N927XJ,...,134.0,1.0,1028.0,5,0.0,0.0,112.0,0.0,0.0,NaN
4,2018,3,7,21,6,2018-07-21,9E,20363,9E,N309PQ,...,145.0,1.0,1028.0,5,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
flights_MIA_201807.columns

Index(['YEAR', 'QUARTER', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE',
       'OP_UNIQUE_CARRIER', 'OP_CARRIER_AIRLINE_ID', 'OP_CARRIER', 'TAIL_NUM',
       'OP_CARRIER_FL_NUM', 'ORIGIN_AIRPORT_ID', 'ORIGIN_AIRPORT_SEQ_ID',
       'ORIGIN_CITY_MARKET_ID', 'ORIGIN', 'ORIGIN_CITY_NAME',
       'DEST_AIRPORT_ID', 'DEST_AIRPORT_SEQ_ID', 'DEST_CITY_MARKET_ID', 'DEST',
       'DEST_CITY_NAME', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY',
       'DEP_DELAY_GROUP', 'DEP_TIME_BLK', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'ARR_DEL15', 'ARR_DELAY_GROUP', 'ARR_TIME_BLK', 'CANCELLED',
       'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'FLIGHTS', 'DISTANCE',
       'DISTANCE_GROUP', 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY',
       'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY', 'Unnamed: 50'],
      dtype='object')

In [7]:
# subset flights that are from/to Miami from/to LA or New York
# flights from Miami
flights_MIA_201807[(flights_MIA_201807['ORIGIN_CITY_NAME'] == 'Miami, FL') & ((flights_MIA_201807['DEST_CITY_NAME'] == 'Los Angeles, CA') | (flights_MIA_201807['DEST_CITY_NAME'] == 'New York, NY'))]

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,...,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 50
26948,2018,3,7,1,7,2018-07-01,AA,19805,AA,N758AN,...,285.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26949,2018,3,7,2,1,2018-07-02,AA,19805,AA,N758AN,...,292.0,1.0,2342.0,10,0.0,0.0,111.0,0.0,116.0,NaN
26950,2018,3,7,3,2,2018-07-03,AA,19805,AA,N788AN,...,281.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26951,2018,3,7,4,3,2018-07-04,AA,19805,AA,N752AN,...,281.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26952,2018,3,7,5,4,2018-07-05,AA,19805,AA,N771AN,...,273.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26953,2018,3,7,6,5,2018-07-06,AA,19805,AA,N784AN,...,270.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26954,2018,3,7,7,6,2018-07-07,AA,19805,AA,N774AN,...,288.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26955,2018,3,7,8,7,2018-07-08,AA,19805,AA,N762AN,...,272.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26956,2018,3,7,9,1,2018-07-09,AA,19805,AA,N787AL,...,271.0,1.0,2342.0,10,264.0,0.0,0.0,0.0,0.0,NaN
26957,2018,3,7,10,2,2018-07-10,AA,19805,AA,N772AN,...,274.0,1.0,2342.0,10,0.0,120.0,0.0,0.0,16.0,NaN
26958,2018,3,7,11,3,2018-07-11,AA,19805,AA,N779AN,...,287.0,1.0,2342.0,10,0.0,57.0,1.0,0.0,37.0,NaN
26959,2018,3,7,12,4,2018-07-12,AA,19805,AA,N781AN,...,272.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26960,2018,3,7,13,5,2018-07-13,AA,19805,AA,N774AN,...,265.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26961,2018,3,7,14,6,2018-07-14,AA,19805,AA,N770AN,...,266.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26962,2018,3,7,15,7,2018-07-15,AA,19805,AA,N767AJ,...,265.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26963,2018,3,7,16,1,2018-07-16,AA,19805,AA,N774AN,...,259.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26964,2018,3,7,17,2,2018-07-17,AA,19805,AA,N784AN,...,266.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26965,2018,3,7,18,3,2018-07-18,AA,19805,AA,N797AN,...,267.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26966,2018,3,7,19,4,2018-07-19,AA,19805,AA,N793AN,...,267.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26967,2018,3,7,20,5,2018-07-20,AA,19805,AA,N752AN,...,272.0,1.0,2342.0,10,0.0,33.0,90.0,0.0,0.0,NaN
26968,2018,3,7,21,6,2018-07-21,AA,19805,AA,N770AN,...,271.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26969,2018,3,7,22,7,2018-07-22,AA,19805,AA,N777AN,...,267.0,1.0,2342.0,10,32.0,0.0,0.0,0.0,0.0,NaN
26970,2018,3,7,23,1,2018-07-23,AA,19805,AA,N775AN,...,281.0,1.0,2342.0,10,0.0,148.0,2.0,0.0,0.0,NaN
26971,2018,3,7,24,2,2018-07-24,AA,19805,AA,N772AN,...,273.0,1.0,2342.0,10,0.0,20.0,0.0,0.0,0.0,NaN
26972,2018,3,7,25,3,2018-07-25,AA,19805,AA,N791AN,...,274.0,1.0,2342.0,10,0.0,80.0,0.0,0.0,6.0,NaN
26973,2018,3,7,26,4,2018-07-26,AA,19805,AA,N776AN,...,287.0,1.0,2342.0,10,42.0,0.0,21.0,0.0,1.0,NaN
26974,2018,3,7,27,5,2018-07-27,AA,19805,AA,N766AN,...,279.0,1.0,2342.0,10,108.0,0.0,14.0,0.0,0.0,NaN
26975,2018,3,7,28,6,2018-07-28,AA,19805,AA,N775AN,...,275.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26976,2018,3,7,29,7,2018-07-29,AA,19805,AA,N755AN,...,278.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
26977,2018,3,7,30,1,2018-07-30,AA,19805,AA,N793AN,...,296.0,1.0,2342.0,10,166.0,0.0,7.0,0.0,38.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84824,2018,3,7,20,5,2018-07-20,DL,19790,DL,N865DN,...,156.0,1.0,1089.0,5,NaN,NaN,NaN,NaN,NaN,NaN
84825,2018,3,7,20,5,2018-07-20,DL,19790,DL,N376NW,...,132.0,1.0,1089.0,5,8.0,0.0,0.0,0.0,91.0,NaN
84832,2018,3,7,20,5,2018-07-20,DL,19790,DL,N321US,...,144.0,1.0,1089.0,5,NaN,NaN,NaN,NaN,NaN,NaN
84874,2018,3,7,20,5,2018-07-20,DL,19790,DL,N358NB,...,146.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
85110,2018,3,7,20,5,2018-07-20,DL,19790,DL,N381DN,...,284.0,1.0,2342.0,10,NaN,NaN,NaN,NaN,NaN,NaN
86325,2018,3,7,1,7,2018-07-01,YX,20452,YX,N402YX,...,146.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86326,2018,3,7,2,1,2018-07-02,YX,20452,YX,N420YX,...,150.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86327,2018,3,7,5,4,2018-07-05,YX,20452,YX,N436YX,...,152.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86328,2018,3,7,6,5,2018-07-06,YX,20452,YX,N435YX,...,180.0,1.0,1096.0,5,0.0,0.0,20.0,0.0,0.0,NaN
86329,2018,3,7,8,7,2018-07-08,YX,20452,YX,N446YX,...,149.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86330,2018,3,7,9,1,2018-07-09,YX,20452,YX,N410YX,...,158.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86331,2018,3,7,10,2,2018-07-10,YX,20452,YX,N403YX,...,154.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86332,2018,3,7,11,3,2018-07-11,YX,20452,YX,N416YX,...,144.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86333,2018,3,7,12,4,2018-07-12,YX,20452,YX,N446YX,...,158.0,1.0,1096.0,5,0.0,0.0,16.0,0.0,0.0,NaN
86334,2018,3,7,13,5,2018-07-13,YX,20452,YX,N444YX,...,155.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86335,2018,3,7,15,7,2018-07-15,YX,20452,YX,N447YX,...,148.0,1.0,1096.0,5,28.0,0.0,0.0,0.0,0.0,NaN
86336,2018,3,7,16,1,2018-07-16,YX,20452,YX,N427YX,...,153.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86337,2018,3,7,17,2,2018-07-17,YX,20452,YX,N110HQ,...,159.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86338,2018,3,7,18,3,2018-07-18,YX,20452,YX,N434YX,...,146.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86339,2018,3,7,19,4,2018-07-19,YX,20452,YX,N443YX,...,155.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86340,2018,3,7,20,5,2018-07-20,YX,20452,YX,N406YX,...,147.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86341,2018,3,7,22,7,2018-07-22,YX,20452,YX,N445YX,...,152.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86342,2018,3,7,23,1,2018-07-23,YX,20452,YX,N403YX,...,141.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86343,2018,3,7,24,2,2018-07-24,YX,20452,YX,N437YX,...,147.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86344,2018,3,7,25,3,2018-07-25,YX,20452,YX,N429YX,...,NaN,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86345,2018,3,7,26,4,2018-07-26,YX,20452,YX,N435YX,...,143.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86346,2018,3,7,27,5,2018-07-27,YX,20452,YX,N417YX,...,153.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86347,2018,3,7,29,7,2018-07-29,YX,20452,YX,N403YX,...,157.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86348,2018,3,7,30,1,2018-07-30,YX,20452,YX,N402YX,...,148.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN
86349,2018,3,7,31,2,2018-07-31,YX,20452,YX,N417YX,...,144.0,1.0,1096.0,5,NaN,NaN,NaN,NaN,NaN,NaN